apiVersion: v1
kind: Service
metadata:
    name: "akswithapim-3511"
    labels:
        app: "akswithapim-3511"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akswithapim-3511"