on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jimacrtest.azurecr.io
        username: ${{ secrets.acr_jimacrtest_username }}
        password: ${{ secrets.acr_jimacrtest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jimacrtest.azurecr.io/akswithapim:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push jimacrtest.azurecr.io/akswithapim:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akswithapim_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akswithapimgithub | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akswithapimgithub`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akswithapimgithub
        container-registry-url: jimacrtest.azurecr.io
        container-registry-username: ${{ secrets.acr_jimacrtest_username }}
        container-registry-password: ${{ secrets.acr_jimacrtest_password }}
        secret-name: akswithapimdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akswithapimgithub
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          jimacrtest.azurecr.io/akswithapim:${{ github.sha }}
        imagepullsecrets: |
          akswithapimdockerauth
